name: Build and push new Docker image
on: [push]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Docker Build & Push
        uses: mr-smithers-excellent/docker-build-push@v5.6
        with:
          image: duckmade-graphql-api-server
          registry: ghcr.io
          addLatest: ${{ github.ref_name == 'main' }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
